### ISSUE TITLE
No shadows on iOS

### ISSUE THREAD

**Issue by erkanarslan** [Especializa/nativescript-ng-shadow#9]
### Make sure to check the demo app(s) for sample usage
It doesn't build

### If the demo apps cannot help and there is no issue for your problem, tell us about it
No shadows on iOS. I set the shadow with `shadow="2"` in xml file.

### Which platform(s) does your issue occur on?
- iOS 11
- emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.3.1
- Cross-platform modules: 3.3.0
- Runtime(s): 3.3.0 for iOS

**Comment by berardo** [comment]
Hi @erkanarslan, please try the just released version 2.0.0.
This issue should be addressed.
Otherwise, please let me know.
Thanks

**Comment by erkanarslan** [comment]
Shadow is applied strangely both on iOS and Android.

Let me show you my xml and css codes first:

In this xml important thing is that there is a top element which contains two children: info box at the top which should have no shadow and a card that should have the shadow.

````xml
<stack-layout class="item" [visible]="!item.collapsed" shadow="10">
	<flexbox-layout class="top-info">
		<label class="fa item-icon" [ngClass]="iconColors[item.type]" [text]="icons[item.type]"></label>
		<label class="item-date" [text]="item.date | date:'d MMMM, HH:mm'"></label>
	</flexbox-layout>
	<stack-layout (tap)="itemTapped(item)" class="item-card">
		<flexbox-layout class="item-title">
			<label class="fa priority priority-{{item.priority}}-text" text="&#xf111;" [visible]="item.type != 'event'"></label>
			<label [text]="item.title"></label>
		</flexbox-layout>
		<flexbox-layout class="item-body">
			<label *ngIf="item.type == 'event'" class="fa" text="&#xf017;"></label>
			<label *ngIf="item.type == 'event' && !item.item.allDay" [text]="(item.item.start | date:'HH:mm') + (item.item.end ? ' - ' + (item.item.end | date:'HH:mm') : '')" class="mr8"></label>
			<label *ngIf="item.type == 'event' && item.item.allDay" text="Tüm Gün"></label>
			<label *ngIf="item.item.state" class="badge" [ngStyle]="{'background-color' : item.item.state.color, color : item.item.state.textColor}" [text]="item.item.state.name"></label>
			<label *ngIf="item.item.group" class="fa pl8" text="&#xf0c0;"></label>
			<label *ngIf="item.item.group" [text]="item.item.group.name"></label>
		</flexbox-layout>
	</stack-layout>
</stack-layout>
````

I tried putting shadow directive on the element with item-card` class first but it didn't create shadow on android and shadow was on inner elements on iOS. Here are screenshots:



After that, I tried putting the directive on the top element which creates shadow on android but I only want it to be visible on item-card element. On iOS shadow is again applied on child elements rather than the element itself:


I want the shadow to be applied around card-item element.

````css
.item-card {
	border-width: 1px;
	border-color: #ddd;
	border-radius: 8;
	margin-top: 4;
}

.item-title {
	padding: 8;
	background-color: #eee;
	border-bottom-width: 1px;
	border-bottom-color: #ddd;
	align-items: center;
	font-size: 14;
	border-radius: 8 8 0 0;
}

.item-title .priority {
	flex-shrink: 0;
	margin-right: 5;
}

.item-body {
	font-size: 12;
	padding: 12 8;
	align-items: center;
}
````
